import "./globals.css";
import styles from "./main.module.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "what movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.layout}>
          <header className={styles.title}>
            <h1>뭐 보까?</h1>
          </header>
          <main id="main-container">{children}</main>
        </div>
      </body>
    </html>
  );
}
